spring.application.name=Core_Mini_Banking_System-1

server.port=8071
spring.datasource.url=jdbc:postgresql://localhost:5432/mini_banking
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true